version: '3.6'
services:
  Elasticsearch:
    image: elasticsearch:${ELK}
    container_name: elasticsearch
    restart: always
    volumes:
    - ./elastic/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    ports:
    - '9200:9200'
    - '9300:9300'
    networks:
      - elk

  Logstash:
    image: logstash:${ELK}
    container_name: logstash
    restart: always
    volumes:
    - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
    - ./logstash/pipeline.yml:/usr/share/logstash/pipeline.yml
    depends_on:
      - Elasticsearch
    ports:
    - "5044:5044"
    - "5000:5000/tcp"
    - '9600:9600'
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  Kibana:
    image: kibana:${ELK}
    container_name: kibana
    restart: always
    volumes:
    - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
    - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - Elasticsearch
    networks:
      - elk

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - elk
    depends_on:
      - Elasticsearch


volumes:
  elastic: {}

networks:
  elk:
