---
- name: install docker in all instance
  hosts: slaves
  become: yes


  tasks:
    - name: install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: install packages required by docker
      apt:
        update_cache: yes
        state: latest
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gpg-agent
          - software-properties-common
          - python3-pip
          - python3-setuptools
          - virtualenv
          - default-jdk

    - name: docker gpg apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: add docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: install docker
      apt:
        update_cache: yes
        state: latest
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io

##### Docker SDK for Python

    - name: install 'Docker SDK for Python'
      pip:
        name: docker

##### Run Jenkins

    - name: Run Jenkins
      docker_container:
        name: Jenkins-master
        image: jenkins/jenkins:lts
      #  network_mode: bridge
        ports:
          - 8080:8080
          - 50000:50000
        restart_policy: always
        privileged: yes
        volumes:
#          - jenkins_home:/var/jenkins_home
          - /var/run/docker.sock:/var/run/docker.sock
          - /usr/local/bin:/user/bin
#          - /var/jenkins_home:~/.jenkins

    - name: Docker without sudo
      shell: groupadd docker && usermod -aG docker ubuntu && newgrp docker

#    - name: Result
#      shell: docker ps
#      register: result
#
#    - debug:
#        var: result

    - name: Unlock jenkins
      shell: sleep 20 && docker exec -it Jenkins-master /bin/sh -c 'cat /var/jenkins_home/secrets/initialAdminPassword'
      register: jenkins_pwd

    - debug:
        var: jenkins_pwd
