---
- hosts: all
  become: true
  tasks:

    - name: install pip
      apt:
        update_cache: yes
        state: latest
        name:
          - python3-pip
          - python3-setuptools

    - name: Install agent
      include_role:
        name:  community.zabbix.zabbix_agent
      tags:
        - install

    - name: Create a new host or update an existing host's info
      local_action:
        module: community.zabbix.zabbix_host
        server_url: "{{ zabbix_url }}"
        login_user: "{{ zabbix_api_user }}"
        login_password: "{{ zabbix_api_pass }}"
        host_name: "{{ zabbix_agent_visible_hostname }}"
        visible_name: "{{ zabbix_agent_visible_hostname }}"
        description: "{{   zabbix_host_description | default('') }} OS: {{  ansible_distribution | default('') }} {{  ansible_distribution_version | default('') }}"
        host_groups: Linux servers
        link_templates: "{{ zabbix_link_templates }}"
        status: "{{  zabbix_host_status }}"
        status: enabled
        state: present
        inventory_mode: disabled
        interfaces:
          - type: "{{ zabbix_interface_type }}"
            main: 1
            useip: "{{ zabbix_interface_use_ip }}"
            ip: "{{ zabbix_interface_ip }}"
            port: "{{ zabbix_interface_port }}"
      run_once: true
      tags:
        - add-host

    - name: restart zabbix-agents
      shell: systemctl restart zabbix-agent.service
