---
- name: Jenkins Master
  hosts: localhost
  become: yes


  tasks:
    - name: install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: install packages required by docker
      apt:
        update_cache: yes
        state: latest
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gpg-agent
          - software-properties-common
          - python3-pip
          - python3-setuptools
          - virtualenv
          - default-jdk

    - name: docker gpg apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: add docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: install docker
      apt:
        update_cache: yes
        state: latest
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io

##### Docker SDK for Python

    - name: install 'Docker SDK for Python'
      pip:
        name: docker

##### Access to the sock  from jenkins
    - name: Unlock jenkins
      shell: chmod 666 /var/run/docker.sock

##### Run Jenkins
    - name: Run Jenkins Master
      docker_container:
        name: jenkins-master
        image: megadocker2000/study:jenkins
        ports:
          - 8080:8080
          - 50000:50000
        restart_policy: always
        privileged: yes
        volumes:
          - /usr/bin/docker:/usr/bin/docker
          - /var/run/docker.sock:/var/run/docker.sock

#############

    - name: Docker without sudo
      shell: usermod -aG docker u1
      ignore_errors: yes

###### Run slaves

    - name: Run Jenkins Slave1
      docker_container:
        name: slave1
        image: bibinwilson/jenkins-slave
        ports:
          - "0.0.0.0:1121:22"
        restart_policy: always
        privileged: yes
        volumes:
          - /usr/bin/docker:/usr/bin/docker
          - /var/run/docker.sock:/var/run/docker.sock

    - name: Run Jenkins Slave2
      docker_container:
        name: slave2
        image: bibinwilson/jenkins-slave
        ports:
          - "0.0.0.0:1222:22"
        restart_policy: always
        privileged: yes
        volumes:
          - /usr/bin/docker:/usr/bin/docker
          - /var/run/docker.sock:/var/run/docker.sock

##############

    - name: Unlock jenkins
      shell: docker logs jenkins-master
      #docker exec -it jenkins-master /bin/sh -c 'cat /var/jenkins_home/secrets/initialAdminPassword'
      #Strange, works on AWS, but not local
      ignore_errors: yes
      register: jenkins_pwd

    - debug:
        var: jenkins_pwd
